In [1]:
from glio.data import DSTorch
from glio.loaders.image import read
from glio.transforms import ToChannels
# from ..data import DSTorch
# from ..loaders.image import read
# from ..transforms import ToChannels
from torchvision.transforms import v2

MEAN = (0.24678757306068175, 0.24703404547706728, 0.24739312260381638)
STD = (0.24678757306068175, 0.24703404547706728, 0.24739312260381638)
loader = read
def get_dataset(path = "D:/datasets/it1244-brain-tumor-dataset/data", loader = v2.Compose([read, ToChannels(3)])):
    ds = DSTorch.DSClassification()
    with open(f"{path}/train/data.csv", 'r') as f:
        for i, line in enumerate(f):
            num, label = line.strip().replace("\ufeff", '').split(',')
            ds.add_sample(f"{path}/train/{num}.jpg", target = label, loader=loader)
    return ds
ds = get_dataset()
ds[0]


(tensor([[[0.0000, 0.0549, 0.1176,  ..., 0.0078, 0.0078, 0.0078],
          [0.0196, 0.0078, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0510, 0.0000, 0.0353,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0235, 0.0235, 0.0235,  ..., 0.0196, 0.0196, 0.0196],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0510, 0.0510, 0.0510,  ..., 0.0471, 0.0471, 0.0471]],
 
         [[0.1608, 0.2275, 0.2745,  ..., 0.2000, 0.2000, 0.2000],
          [0.1961, 0.1725, 0.1294,  ..., 0.2000, 0.2000, 0.2000],
          [0.2275, 0.1608, 0.1882,  ..., 0.1922, 0.1922, 0.1922],
          ...,
          [0.0275, 0.0275, 0.0275,  ..., 0.0314, 0.0314, 0.0314],
          [0.0157, 0.0157, 0.0157,  ..., 0.0235, 0.0235, 0.0235],
          [0.0902, 0.0902, 0.0902,  ..., 0.0980, 0.0980, 0.0980]],
 
         [[0.4235, 0.4824, 0.5176,  ..., 0.3569, 0.3569, 0.3569],
          [0.4275, 0.4000, 0.3451,  ..., 0.3843, 0.3843, 0.3843],
          [0.3922, 0.3255, 0.3412,  ...,

In [2]:
ds.add_loader(v2.Resize((224,224)))
import torch
torch.set_printoptions(precision=10)
mean, std = ds.get_mean_std(10000, 16)
print(mean)
print(std)

d:\miniconda3\envs\pytorch311\Lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(


tensor([0.2466959655, 0.2469369471, 0.2472953051])
tensor([0.2389927208, 0.2390660942, 0.2392502129])


In [3]:
ds.samples[0].loader.transforms

(Compose(
       <function read at 0x00000218448E3D80>
       ToChannels()
 ),
 Resize(size=[224, 224], interpolation=InterpolationMode.BILINEAR, antialias=warn))